name: watermeter
description: Another personal data assistant for XDU.
publish_to: "none"
version: 1.4.0-dev+24

environment:
  sdk: ">=3.0.0"

dependencies:
  dio: ^5.0.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  synchronized: ^3.1.0+1
  # Stroage Cache
  shared_preferences: ^2.0.15
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.3
  path_provider: ^2.0.11
  json_annotation: ^4.8.0
  share_plus: ^10.0.1
  # Deal with html
  html: ^0.15.4
  charset_converter: ^2.2.1
  # Setting
  settings_ui: ^2.0.2
  # Homepage
  easy_refresh: ^3.3.0+1
  sn_progress_dialog: ^1.1.3
  fluttertoast: ^8.2.2
  extended_nested_scroll_view: ^6.1.2
  # Others
  url_launcher: ^6.1.6
  jiffy: ^6.1.0
  auto_size_text: ^3.0.0
  async: ^2.10.0 # For AsyncMemoizer
  graphic: ^2.2.0
  restart_app: ^1.2.1
  calendar_date_picker2: ^1.0.6
  cached_network_image: ^3.2.3
  qr_flutter: ^4.1.0
  data_table_2: ^2.5.1
  flutter_native_splash: ^2.3.1
  get:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl:
  package_info_plus: ^8.0.0
  flutter_markdown: ^0.7.2
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  vector_graphics: ^1.1.11+1
  vector_graphics_compiler: ^1.1.11+1
  styled_widget: ^0.4.1
  file_picker: ^8.0.3
  chinese_font_library: ^1.1.0
  ming_cute_icons: ^0.0.1
  timelines: ^0.1.0
  based_split_view: ^1.2.0
  disclosure: ^2.2.0 
  pinyin: ^3.3.0
  content_resolver: ^0.3.1
  # Homepage Widget
  home_widget: ^0.6.0
  image: ^4.2.0
  catcher_2: ^2.0.0
  receive_sharing_intent:
    git:
      url: https://github.com/ilzc/receive_sharing_intent
  # XDU Planet
  flutter_widget_from_html_core: any
  fwfh_cached_network_image: ^0.14.3
  fwfh_url_launcher: ^0.9.1
  latext: ^0.4.1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.1.0
  pigeon: ^20.0.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/Icon-App-iTunes.png"
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Icon-App-iTunes.png
    - assets/Empty-Cover.jpg
    - assets/icon.png
    - assets/CP1919.svg.vec
    - assets/Icon-App-iTunes-Background.png